### ISSUE TITLE
TypeError (empty prices)

### ISSUE THREAD

**Issue by Robert27** [neuland-ingolstadt/mensa-widget#1]
The widget is unable to process empty prices, which results in the error message shown below

![A7882279-E0F9-4470-B5B6-63467276C8D8](https://user-images.githubusercontent.com/53063597/162899581-e1f50422-fdb6-43aa-a7d3-999afcd21e50.jpeg)

**Comment by alexhorn** [comment]
Unfortunately I can't reproduce this, but it should be an easy fix
